[build]
  command = "npm install"
  functions = "api"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
